# Generated by Django 2.1.5 on 2019-10-16 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('aircraft_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('airline_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('gate_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_gates', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookedGate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_gates', models.IntegerField()),
                ('airline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mogul.Airline')),
                ('airport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mogul.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet_id', models.IntegerField()),
                ('aircraft_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mogul.Aircraft')),
                ('airline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mogul.Airline')),
            ],
        ),
        migrations.AddField(
            model_name='airline',
            name='base_airport_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mogul.Airport'),
        ),
        migrations.AlterUniqueTogether(
            name='fleet',
            unique_together={('fleet_id', 'airline_id')},
        ),
        migrations.AlterUniqueTogether(
            name='bookedgate',
            unique_together={('airport_id', 'airline_id')},
        ),
    ]
