# Generated by Django 2.1.5 on 2019-10-16 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mogul', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_gates', models.IntegerField()),
                ('airline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mogul.Airline')),
                ('hub_airport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mogul.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('flight_no', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('aircraft_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mogul.Aircraft')),
                ('airline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mogul.Airline')),
                ('base_airport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mogul.Hub')),
                ('destination_airport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mogul.Airport')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='hub',
            unique_together={('hub_airport_id', 'airline_id')},
        ),
    ]
