# Generated by Django 2.1.5 on 2019-10-16 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mogul', '0004_auto_20191016_2110'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='route',
            name='aircraft_id',
        ),
        migrations.RemoveField(
            model_name='route',
            name='airline_id',
        ),
        migrations.RemoveField(
            model_name='route',
            name='base_airport_id',
        ),
        migrations.RemoveField(
            model_name='route',
            name='destination_airport_id',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
