# Generated by Django 2.1.5 on 2019-10-16 16:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('mogul', '0006_auto_20191016_2114'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aircraft',
            table='aircraft',
        ),
        migrations.AlterModelTable(
            name='airline',
            table='airline',
        ),
        migrations.AlterModelTable(
            name='airport',
            table='airport',
        ),
        migrations.AlterModelTable(
            name='bookedgate',
            table='bookedgate',
        ),
        migrations.AlterModelTable(
            name='fleet',
            table='fleet',
        ),
        migrations.AlterModelTable(
            name='hub',
            table='hub',
        ),
        migrations.AlterModelTable(
            name='route',
            table='route',
        ),
    ]
