# Generated by Django 2.1.5 on 2019-10-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mogul', '0007_auto_20191016_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='base_airport_id',
        ),
    ]
