# Generated by Django 2.1.5 on 2019-10-16 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mogul', '0008_remove_airline_base_airport_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fleet',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='fleet',
            name='aircraft_id',
        ),
        migrations.RemoveField(
            model_name='fleet',
            name='airline_id',
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='route',
            name='airline_id',
        ),
        migrations.RemoveField(
            model_name='route',
            name='base_airport_id',
        ),
        migrations.RemoveField(
            model_name='route',
            name='destination_airport_id',
        ),
        migrations.RemoveField(
            model_name='route',
            name='fleet_id',
        ),
        migrations.DeleteModel(
            name='Fleet',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
