# Generated by Django 2.1.5 on 2019-10-16 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mogul', '0009_auto_20191016_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet_id', models.IntegerField()),
                ('aircraft_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mogul.Aircraft')),
                ('airline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mogul.Airline')),
            ],
            options={
                'db_table': 'fleet',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('airline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mogul.Airline')),
                ('base_airport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mogul.Hub')),
                ('destination_airport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mogul.Airport')),
                ('fleet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mogul.Fleet')),
            ],
            options={
                'db_table': 'route',
            },
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('airline_id', 'flight_no')},
        ),
        migrations.AlterUniqueTogether(
            name='fleet',
            unique_together={('fleet_id', 'airline_id')},
        ),
    ]
