# Generated by Django 2.1.5 on 2019-10-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mogul', '0010_auto_20191016_2250'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hub',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='hub',
            name='airline_id',
        ),
        migrations.RemoveField(
            model_name='hub',
            name='hub_airport_id',
        ),
        migrations.RemoveField(
            model_name='route',
            name='base_airport_id',
        ),
        migrations.DeleteModel(
            name='Hub',
        ),
    ]
