# Generated by Django 2.1.5 on 2019-10-16 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mogul', '0011_auto_20191016_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mogul.Airport'),
        ),
    ]
