# Generated by Django 2.1.5 on 2019-10-16 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mogul', '0012_airline_airport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedgate',
            old_name='airline_id',
            new_name='airline',
        ),
        migrations.RenameField(
            model_name='bookedgate',
            old_name='airport_id',
            new_name='airport',
        ),
        migrations.RenameField(
            model_name='fleet',
            old_name='aircraft_id',
            new_name='aircraft',
        ),
        migrations.RenameField(
            model_name='fleet',
            old_name='airline_id',
            new_name='airline',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='airline_id',
            new_name='airline',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='destination_airport_id',
            new_name='airport',
        ),
        migrations.AlterUniqueTogether(
            name='bookedgate',
            unique_together={('airport', 'airline')},
        ),
        migrations.AlterUniqueTogether(
            name='fleet',
            unique_together={('fleet_id', 'airline')},
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('airline', 'flight_no')},
        ),
    ]
