# Generated by Django 2.1.5 on 2019-10-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mogul', '0013_auto_20191016_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='airport',
            new_name='dest_airport',
        ),
    ]
