# Generated by Django 2.1.5 on 2019-10-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mogul', '0014_auto_20191016_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='fleet_id',
            new_name='fleet',
        ),
    ]
