# Generated by Django 2.1.5 on 2019-10-17 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mogul', '0017_auto_20191017_0920'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fleet',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='fleet',
            name='aircraft',
        ),
        migrations.RemoveField(
            model_name='fleet',
            name='airline',
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='route',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='route',
            name='dest_airport',
        ),
        migrations.RemoveField(
            model_name='route',
            name='fleet',
        ),
        migrations.DeleteModel(
            name='Fleet',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
