# Generated by Django 2.1.5 on 2019-10-21 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mogul', '0019_auto_20191017_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='flight_no',
            new_name='flight_id',
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('airline', 'flight_id')},
        ),
    ]
