# Generated by Django 2.1.5 on 2019-10-21 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mogul', '0020_auto_20191021_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('DOB', models.DateField()),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('seat_no', models.IntegerField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mogul.Customer')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mogul.Route')),
            ],
            options={
                'db_table': 'passenger',
            },
        ),
    ]
