# Generated by Django 2.1.5 on 2019-10-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogul', '0021_customer_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='id',
        ),
        migrations.AlterField(
            model_name='route',
            name='flight_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
