# Generated by Django 2.1.5 on 2019-10-21 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mogul', '0023_auto_20191021_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('DOB', models.DateField()),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('seat_no', models.IntegerField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mogul.Customer')),
            ],
            options={
                'db_table': 'passenger',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('flight_id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mogul.Airline')),
                ('dest_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mogul.Airport')),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mogul.Fleet')),
            ],
            options={
                'db_table': 'route',
            },
        ),
        migrations.AddField(
            model_name='passenger',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mogul.Route'),
        ),
    ]
