# Generated by Django 2.1.5 on 2019-10-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogul', '0026_auto_20191021_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
